### ISSUE TITLE
In BA, est_{r+1} needs to be set to v when v != coin

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerBFT-Python#8]
The binary agreement algorithm requires that `est` be set to `v` if `len(values) == 1`, but the [current code](https://github.com/initc3/HoneyBadgerBFT-Python/blob/dev/honeybadgerbft/core/binaryagreement.py#L142) is more restrictive as it only sets `est = v` if `v == s`: If `v != s` then `est` is simply not set and therefore remains the same for the next round:
  
```python
        # ...
        s = coin(r)

        if len(values) == 1:
            v = next(iter(values))
            if v == s:
                if already_decided is None:
                    already_decided = v
                    decide(v)
                elif already_decided == v:
                    _thread_recv.kill()
                    return
                est = v
        else:
            est = s
        r += 1
````

So if we want to follow the description of the algorithm found in the Honey Badger paper and in *Moustefaoui et al.* the above code should be modified to something like:

 
```python
        # ...
        s = coin(r)

        if len(values) == 1:
            v = next(iter(values))
            if v == s:
                if already_decided is None:
                    already_decided = v
                    decide(v)
                elif already_decided == v:
                    _thread_recv.kill()
                    return
            est = v
        else:
            est = s
        r += 1
````

**NOTE** It would be good to have a test that catches this problem.

**Comment by amiller** [comment]
Oof. Looks like an indentation mistake. Good catch. Maybe it should be an "else" for clarity?

```python
        if len(values) == 1:
            v = next(iter(values))
            if v == s:
                # ... definitely decide on v
            else: 
                est = v
```

Definitely also deserves a test. I wonder if there is a scenario where this could cause a liveness failure?

**Comment by sbellem** [comment]
> Maybe it should be an "else" for clarity?
> 
> ```python
> if len(values) == 1:
>     v = next(iter(values))
>     if v == s:
>         # ... definitely decide on v
>     else: 
>         est = v
> ```
I like the way it is in the Honeybadger paper:

> ```
> if vals = {b}, then
>     est_{r+1} := b
>     if (b = s%2) then output b
> else est_{r+1} := s%2
> ```

```python
if len(values) == 1:
    v = next(iter(values))
    est = v
    if v == s:
        # ... definitely decide on v
```

This way it is quite clear that `est` gets set to `v` as long as `len(values) == 1` and regardless of whether `v` is equal to the coin or not.

**Comment by sbellem** [comment]
> Definitely also deserves a test.

For testing purposes I am wondering whether isolating that code in a separate function would be a good idea. For testing it would definitely make things easier.

As an example:

```python
# phase 3 in Mostefaoui et al
def local_compute_phase(coin, r, values, already_decided, decide):
    # Block until receiving the common coin value
    s = coin(r)
    if len(values) == 1:
        v = next(iter(values))
        est = v
        if v == s:
            if already_decided is None:
                already_decided = v
                decide(v)
            elif already_decided == v:
                # Here corresponds to a proof that if one party
                # decides at round r, then in all the following
                # rounds, everybody will propose r as an
                # estimation. (Lemma 2, Lemma 1) An abandoned
                # party is a party who has decided but no enough
                # peers to help him end the loop.  Lemma: # of
                # abandoned party <= t
                raise AbandonedNodeError
    else:
        est = s
    return est, already_decided
```

**Comment by amiller** [comment]
This refactor looks useful! Would it be more useful still if there was no blocking at all in this function?

**Comment by sbellem** [comment]
> Would it be more useful still if there was no blocking at all in this function?

Oh yes, this is how I did it first! I have put the "getting the coin" step in it just so it would match phase 3 described in Mostefaoui et al paper.  :)

**Comment by sbellem** [comment]
Updated the related PR (#9) such that the local computation phase part of the code, after getting the coin, is isolated.

**Comment by sbellem** [comment]
> I wonder if there is a scenario where this could cause a liveness failure?

Just some thoughts: if we consider the following from _Mostéfaoui et al_, in the proof of Lemma 5:

> Claim. With probability 1, there is a round r at the end of which all the correct processes have the same estimate value. (End of the claim.)
>
> Assuming the claim holds, it follows from Lemma 1 that all the correct processes `p_i` keep their estimate value `est_i = v` and consequently the predicate `values_i = {v}` at line 7 is true at every
round. Due to the common coin CC, it follows that, with probability 1, there is eventually a round in which `random()` outputs `v`. Then, the predicates of the lines 7 and 8 evaluate to true, and all the
correct processes decide.
>
> Proof of the claim. We need to prove that, with probability 1, there is a round at the end of which all the correct processes have the same estimate value. Let us consider a round `r`.
>
> * If all the correct processes execute line 10, they all adopt the value of the common coin at the end of round `r`, and the claim directly follows.
> * Similarly, if all the correct processes execute line 9, they adopt the same value v as their new estimate, and the claim follows.
> * The third case is when some correct processes execute line 9 and adopt the same value v, while others execute line 10 and adopt the same value s.

it is then proved that eventually `s` will equal `v` for some round `r` as `r` goes to infinity. 

So perhaps there would not be a liveness problem with the over-indented code, since it causes a correct node to keep its original `est` value for the next round instead of adopting `v`. That original `est` is equal to `s` or `v`. So in any case it would be _perhaps_ (?) equivalent to the third case, where line 9 is executed, or line 10.

**Comment by sbellem** [comment]
Closing as this was taken care of in #9, which includes a small refactor with tests that fail if `est` is not set (due to an incorrect  indentation).
